#!/bin/bash

xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync && \
xrandr --addmode DP2 1920x1080_60.00 && \
xrandr --output DP2 --mode 1920x1080_60.00 && \
xrandr --output eDP1 --auto --output DP2 --auto --left-of eDP1

feh --bg-scale /home/friendly/.config/wallpaper/wall.jpg
exit 0
